### PR TITLE
expand data request

### PR DESCRIPTION
**Pull request by florianziemen**
Added a computation of the data volume to the data request, and updated a few details.

The computation should render as
image

The switch to .qmd is necessary for quarto to render the folding code correctly.

### CODE REVIEW

**Comment by andrewgettelman** [comment]
I would suggest that this be stamped 'DRAFT Data Request' at the top until an infrastructure group (and maybe the steering group) has discussed it.

Okay, so we are going to ask for HealPix level 9 (13km)? Not level 10 (6km, closer to the native grids of many models). Why 13km? To make it smaller?

You are also asking for zarr and intake-esm catalogs. I think many will need some help with that. I will certainly. Also you want interpolation to standard levels. I was going to leave data on the native levels.

Also, what compression is going to be used? I'm not a big fan of compression that slows down the reading (which most of it has seemed to do), but I'm open to specific suggestions.  

One question: will HealPix work with a non-global grid? We are going to have some regional grids, so there may need to be a diversity of approaches. 

Remember that not everyone has dedicated funding for this: so the more we add requirements the lower the participation. I'd like to see us perhaps focus on getting notebooks/routines/code to read data in heterogenous formats into xarray, and let the user sort it out a bit.  

I like the standard for catalogs, but we may also need to be flexible on zarr v. netCDF, and that may also depend on data center. 

Hope that helps. 

Andrew

**Comment by florianziemen** [comment]
Moin @andrewgettelman ,

Thanks a lot for your valuable questions and suggestions!

I've added draft to the title. Very good point. Most of the specifications, including level 9 and pressure levels stems from @bjorn-stevens . Maybe he can say more. 

Pressure level output would (a) reduce the output quite a bit, and (b) ease comparisons, as people don't have to deal with the peculiarities of the different grids.

For compression, we have had very good experiences with zstd and lz4. A key point in this being well-formed compression chunks. Our initial attempts with compressing full 2D fields in one chunk with deflate (or CMIP6 whole 3D fields) proved bad, but in the nextGEMS Cycle 3 and 4, we used zstd and lz4 with up to 48 horizontal chunks and 3(?) chunks in the vertical, and that seems to work very well. And compression cuts the size of the data in half at no cost in quality. If a bit of rounding was applied before compression, way bigger factors could be reached (and how many digits do we really need on temperature or wind speed?).

For non-global grids, the situation is - hmm. Basically the healpix grid by definition is global, so what you'd do is to store a whole lot of NaN. On the disk, this is not really a problem, as the compressor eats long sequences of NaN for breakfast. In Memory it can be an issue, if you don't subset the data before loading (`cdo` would be an example for a rather poorly suited tool). 
We might want to end with healpix for global, and "bring your own grid" for regional models, as those are very different anyways, but I think that's for a science steering committee to decide. I've stopped analyzing data years ago, so I'd leave these decisions to the people who actually want to work with the data.

I see the point that not every team has dedicated funding, but I've also seen the two previous DYAMOND initiatives, and that's a place I never want to visit again.
DYAMOND Summer is a complete mess on our disks and tapes with a zoo of file formats, variable names, etc., that makes processing and comparing cumbersome. It also sometimes requires fetching a whole dataset from the tapes to read one variable, as data was provided with all variables for one time step in a file. 
For DYAMOND Winter, we spent several person months on trying to standardize the zoo of data that was dumped on our disks - all with mixed results, as we had to more-or-less guess, what's the closest match for the variable at hand, and file formats were anywhere between useful and a proof of human creativity.
On the other hand, in nextGEMS, we have made steps towards consolidation (not really getting there, but hey), and things got a lot better.
If the teams can provide examples of how to convert their data into healpix on pressure levels for comparisons, they can also apply that to their datasets, and do this exercise once instead of hundreds of users doing this one-by-one over the next years (we still have people asking for and analyzing DYAMOND Summer data from about 2018).

The intake catalogs actually are quite easy to create, and make people's lives a lot easier. They also work with netCDF files, so they don't really limit people too much in the ways they store the data.

**Comment by andrewgettelman** [comment]
Thanks @florianziemen for the reply. We do need to have some discussion of this at the infrastructure or the planning level. 

Your comments and experience on trying to harmonize data are very valuable. We want to balance ease of use with ease of providing data. How much we force everything to be in the same format is going to be an interesting line to walk. 

I think pushing catalogs is great, since they are easy to make and flexible. 

Given your comments about doing compression wrong: I think we ought to back off it if we can. It will take some work it seems for each data set to figure this out (maybe it's easier with HealPix and it can be done after conversion to HealPix). 

And as far as regional grids go: we probably do need to have some requirements on providing code to read data into xarray, and we might also want to require some sort of name mapping so that if files are NOT processed to have standard names there is at least a simple way to deal with it. Again, we can discuss this.

We might also think about some tests of data sets we could do in the fall (one 'Standard', one other global, maybe one regional'). 

Happy to discuss further.

**Comment by florianziemen** [comment]
I think we should merge this rather soon-ish to have a better basis for the discussions in the open.
We definitely still need to decide on things like mean vs instantaneous output.

I added a sentence saying that regional models might have a different grid need.

**Review by andrewgettelman — APPROVED** [review]
Fine to publish, yes we should get this out there.

THanks!

Andrew

**Pull request merged**
