### PR TITLE
Add first version of "python packages" talk

### PR DESCRIPTION
**Pull request by lkluft**

### CODE REVIEW

**Review by florianziemen — APPROVED** [review]
Moin!

Looks good. I'd maybe add a slide for a hierarchy of 

'piece of code in .ipynb' -> '.py file with utility functions' in a git repo -> py package that others can easily install.

**Comment by lkluft** [comment]
Yeah, I wasn't sure on what level to start. But I can add a slide or two on packages in general (and maybe PyPI)

**Comment by florianziemen** [comment]
That would be great. I guess, we'll have a well-mixed audience. And skipping a slide is much easier than making it up on the spot...

**Comment by florianziemen** [comment]
thanks!

**Pull request merged**
