### PR TITLE
Rename files to md so github shows a kind-of rendered preview

### PR DESCRIPTION
**Pull request by florianziemen**
This way, github will interpret the markdown in the files when displaying them.

see https://github.com/digital-earths-global-hackathon/planning/blob/test-md-rename/hosting/logistics/agenda_template.md for an example (until this branch is deleted).

### CODE REVIEW

**Review by d70-t — COMMENTED** [review]
I see the desire to have the documents (somewhat) rendered on github.
The main downside is: Quarto will not allow executable content within `.md` files, while it does in `.qmd` files. My understanding is, that Quarto will preprocess `qmd` into `md` before passing it on to pandoc. But if you start with an `md`, this preprocessing doesn't happen.

For the current state (content-wise) this likely is no problem, but we might run into problems later on.

If we're feeling lucky and want to try out new things, an alternative could also be [MySt MD](https://mystmd.org), which is relatively new. It spun off of the MySt Markdown extension which is used by the executable book project and now seems to extend into something similar to Quarto (albeit currently likely with a smaller feature set), but approaching it from the Python side instead of from the R side. It still can produce nice websites and it uses files with the `.md` extension also for executable content. So for the particular use case of this PR, MyStMD is likely better suited.

**Comment by florianziemen** [comment]
Hmm, I'm not so keen on yet another language/system. They all subtly differ and that creates friction in the brain when writing. 

The hack-y version would be to use .md for all plain pages and .qmd for those with interactive parts, if we ever have them.

That's ugly and would require require adapting a bunch of links every now and then when a page has to be moved to .qmd  

I'm not saying that would be the best idea, though.

**Comment by d70-t** [comment]
I'd be totally fine wit quarto as well.

For the links, I think it's not necessary to state the extension in the links when rendering them through quarto. (But it might be necessary for github preview).

**Comment by florianziemen** [comment]
Should we merge then?

**Comment by d70-t** [comment]
I'd personally keep the `qmd`, because I wouldn't expect myself to read a lot on github if there's the rendered webpage as well. But I also wouldn't block this, as I could also live with `md` or even a mixture of `md` and `qmd`.
So I'd leave the decision of merge vs close up to you or other votes.

**Comment by lkluft** [comment]
I also have a slight (but not definite) tendency to keep the `.qmd' extension. The rendered versions on Github may even give a misleading impression of what the actual site looks like. However, if we think this will actually improve accessibility and thus outside contributions, I am fine with the change.

**Comment by florianziemen** [comment]
accidentally pushed the changes directly to main. We don't really need the qmd features in most cases, and md is easier for some contributors.
BTW: qmd with python would require changes in the pipeline, as the default is without py.

**Pull request closed without merging**
